### ISSUE TITLE
React popper example fo react classes

### ISSUE THREAD

**Issue by codeasashu** [popperjs/website#18]
First of all, thank you for open-sourcing such a wonderful library.

On the page https://popper.js.org/react-popper/v2/react-portals/

As a user using reactjs using classes, I am unable put the example provided, in my context. I am seeing `useState` and `useEffect` everywhere and I don't know who it will fit for me in react classes.

Please add an example (if possible) showing how to use `react-popper` in react classes. Thank you :)

**Comment by FezVrasta** [comment]
You can use the render-props API

https://popper.js.org/react-popper/v2/render-props/

**Comment by codeasashu** [comment]
@FezVrasta Yes, I've read the page but it only acts as a reference guide. There is not a single example explaining how to use that. Can there be some code fiddle linked that shows how to use it?

**Comment by FezVrasta** [comment]
https://github.com/popperjs/react-popper/tree/v1.x#usage
